### ISSUE TITLE
AD_09 - create design header

### ISSUE THREAD

**Issue by lisuV** [lisuV/drones#1]
create structure of prj local

**Comment by NastiaZhurakovska** [comment]
![Image](https://github.com/lisuV/drones/assets/163176035/90dc9c61-a124-47ac-95fd-8e7104010cda)

**Comment by NastiaZhurakovska** [comment]
![Image](https://github.com/lisuV/drones/assets/163176035/cf4495e6-1260-49e1-a3c4-416618610cb5)

Header components
